server:
  port: 10001
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos\u5730\u5740
    gateway:
      routes:
        - id: member_route
          uri: lb://memberservice
          predicates:
            - Path=/admin/member/**
          filters:
            - RewritePath=/admin/?(?<segment>.*), /$\{segment}
        - id: product_route
          uri: lb://productservice
          predicates:
            - Path=/admin/product/**
          filters:
            - RewritePath=/admin/?(?<segment>.*), /$\{segment}
        - id: party_route
          uri: lb://partyservice
          predicates:
            - Path=/admin/party/**
          filters:
            - RewritePath=/admin/?(?<segment>.*), /$\{segment}
        - id: admin_route
          uri: lb://renrenfast
          #断言
          predicates:
            - Path=/admin/**
          filters:
            - RewritePath=/admin/?(?<segment>.*), /renren-fast/$\{segment}



