server:
  port: 1000
spring:
  application:
    name: partyservice
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      oss:
        bucket: mall-ljzhang-zian
        endpoint: 
      access-key: 
      secret-key: 



